// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"net/http"
)

// Injectors from wire.go:

func InitializeServer() (*http.Server, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDB(config)
	if err != nil {
		return nil, err
	}
	entityRepository := NewEntityRepository(db)
	findEntity := NewFindEntityUseCase(entityRepository)
	handler := NewFindEntityHandler(findEntity)
	duration := NewRequestTimeout()
	server := NewServer(handler, duration)
	return server, nil
}
